version: '3.3'
services:
  backend:
    image: dto80/se234-lab12
    ports:
      - 8000:8080  

  frontend:
    image: jasmxne/lab10
    ports:
      - 8086:80
    environment:
      - VITE_BASE_URL=http://localhost:8000/
